/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Episodes
         * @description List episodes with optional task_name filter and pagination.
         */
        get: operations["list_episodes_api_episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/episodes/{episode_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Episode
         * @description Get full episode detail including steps.
         */
        get: operations["get_episode_api_episodes__episode_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pool Status
         * @description Return current sandbox pool status.
         *
         *     Returns a graceful response when the engine pool is not available
         *     (e.g., on macOS where Linux kernel features are required).
         */
        get: operations["get_pool_status_api_sandboxes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description List tasks that have been evaluated (from episode history).
         */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task
         * @description Get task info by name (from episode history).
         */
        get: operations["get_task_api_tasks__task_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Telemetry Runs
         * @description List telemetry runs with pagination.
         */
        get: operations["list_telemetry_runs_api_telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Telemetry Run
         * @description Get telemetry run detail with raw metric samples.
         */
        get: operations["get_telemetry_run_api_telemetry__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Return API health status.
         *
         *     Reports whether the engine fully started and whether the SQLite
         *     stores are available for querying.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * EpisodeDetail
         * @description Full episode detail including sandbox info and step data.
         */
        EpisodeDetail: {
            /** Episode Id */
            episode_id: string;
            /** Task Name */
            task_name: string;
            /** Outcome */
            outcome: string;
            /** Score */
            score?: number | null;
            /**
             * Step Count
             * @default 0
             */
            step_count: number;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /**
             * Started At
             * @default 0
             */
            started_at: number;
            /** Ended At */
            ended_at?: number | null;
            /**
             * Sandbox Id
             * @default
             */
            sandbox_id: string;
            /**
             * Is Complete
             * @default 1
             */
            is_complete: number;
            /**
             * Steps
             * @default []
             */
            steps: {
                [key: string]: unknown;
            }[];
        };
        /**
         * EpisodeSummary
         * @description Summary of a single evaluation episode.
         */
        EpisodeSummary: {
            /** Episode Id */
            episode_id: string;
            /** Task Name */
            task_name: string;
            /** Outcome */
            outcome: string;
            /** Score */
            score?: number | null;
            /**
             * Step Count
             * @default 0
             */
            step_count: number;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /**
             * Started At
             * @default 0
             */
            started_at: number;
            /** Ended At */
            ended_at?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Engine Started */
            engine_started: boolean;
            /** Stores Available */
            stores_available: boolean;
        };
        /**
         * PaginatedEpisodes
         * @description Paginated list of episode summaries.
         */
        PaginatedEpisodes: {
            /** Items */
            items: components["schemas"]["EpisodeSummary"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /**
         * PaginatedTasks
         * @description Paginated list of task summaries.
         */
        PaginatedTasks: {
            /** Items */
            items: components["schemas"]["TaskSummary"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /**
         * PaginatedTelemetryRuns
         * @description Paginated list of telemetry run summaries.
         */
        PaginatedTelemetryRuns: {
            /** Items */
            items: components["schemas"]["TelemetryRunSummary"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /**
         * PoolStatus
         * @description Current sandbox pool status.
         */
        PoolStatus: {
            /** Running */
            running: boolean;
            /** Total Sandboxes */
            total_sandboxes: number;
            /**
             * Sandboxes
             * @default []
             */
            sandboxes: components["schemas"]["SandboxInfo"][];
        };
        /**
         * SandboxInfo
         * @description Information about a single sandbox instance.
         */
        SandboxInfo: {
            /** Sandbox Id */
            sandbox_id: string;
            /** Fingerprint */
            fingerprint: string;
            /** State */
            state: string;
        };
        /**
         * TaskSummary
         * @description Summary of a task definition.
         */
        TaskSummary: {
            /** Name */
            name: string;
            /**
             * Runtime
             * @default python3.12
             */
            runtime: string;
            /**
             * Timeout
             * @default 1800
             */
            timeout: number;
            /**
             * Max Steps
             * @default 200
             */
            max_steps: number;
            /**
             * Instructions
             * @default
             */
            instructions: string;
            /**
             * Test Command
             * @default
             */
            test_command: string;
        };
        /**
         * TelemetryRunDetail
         * @description Telemetry run detail with raw metric samples.
         */
        TelemetryRunDetail: {
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * @default 0
             */
            started_at: number;
            /** Ended At */
            ended_at?: number | null;
            /**
             * Total Episodes
             * @default 0
             */
            total_episodes: number;
            /** Throughput Eps Per Min */
            throughput_eps_per_min?: number | null;
            /** Cache Hit Rate */
            cache_hit_rate?: number | null;
            /**
             * Samples
             * @default []
             */
            samples: {
                [key: string]: unknown;
            }[];
        };
        /**
         * TelemetryRunSummary
         * @description Summary of a telemetry collection run.
         */
        TelemetryRunSummary: {
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * @default 0
             */
            started_at: number;
            /** Ended At */
            ended_at?: number | null;
            /**
             * Total Episodes
             * @default 0
             */
            total_episodes: number;
            /** Throughput Eps Per Min */
            throughput_eps_per_min?: number | null;
            /** Cache Hit Rate */
            cache_hit_rate?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WsEnvelope
         * @description WebSocket message envelope.
         *
         *     Every message sent over the WebSocket connection is wrapped in this
         *     envelope.  The ``payload`` dict reuses the same shapes as REST
         *     responses so the codegen pipeline produces TypeScript types for both.
         */
        WsEnvelope: {
            /** Type */
            type: string;
            /** Topic */
            topic: string;
            /** Timestamp */
            timestamp: number;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_episodes_api_episodes_get: {
        parameters: {
            query?: {
                task_name?: string | null;
                /** @description Zero-based offset */
                offset?: number;
                /** @description Max items to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEpisodes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_episode_api_episodes__episode_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pool_status_api_sandboxes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolStatus"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                /** @description Zero-based offset */
                offset?: number;
                /** @description Max items to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTasks"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_tasks__task_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_telemetry_runs_api_telemetry_get: {
        parameters: {
            query?: {
                /** @description Zero-based offset */
                offset?: number;
                /** @description Max items to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTelemetryRuns"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_telemetry_run_api_telemetry__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
