// Auto-generated by openapi-typescript from FastAPI OpenAPI schema.
// Run `pnpm codegen` from web/ to regenerate.
// This placeholder will be replaced by the codegen pipeline in plan 08-03.
export interface paths {}
export interface components {}
export interface operations {}
